### PR TITLE
SBT-fied project dependencies

### PR DESCRIPTION
**Pull request by prassee**

### CODE REVIEW

**Comment by prassee** [comment]
In this pull request I removed makefile and added support for Scala 2.11.x

**Comment by gangeli** [comment]
This pull request appears to just move the build system to sbt, right? I'm happy to fix the Makefile if it's broken, and I'm happy to have an sbt build file alongside the Makefile, but I'm quite strongly opposed to having SBT be the main build system and removing the Makefile altogether.

**Comment by prassee** [comment]
I abide your wish to retain Makefile, but at the same time please be noted
that I have moved the package " edu " in to "src/main/scala" this is made
to have a structure inline with maven.

On Tue, Apr 21, 2015 at 3:32 PM, Gabor Angeli <notifications@github.com>
wrote:

> This pull request appears to just move the build system to sbt, right? I'm
> happy to fix the Makefile if it's broken, and I'm happy to have an sbt
> build file alongside the Makefile, but I'm quite strongly opposed to having
> SBT be the main build system and removing the Makefile altogether.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gangeli/CoreNLP-Scala/pull/1#issuecomment-94727109>.
>



-- 
*Regards*
*Prassee*

**Comment by prassee** [comment]
Please have a look at this pull request containing the changes we discussed over the last pull request

**Comment by gangeli** [comment]
Looking at this closer, it looks like you're just moving files deeper into the directory structure. In large projects with many languages and many tests, this makes sense. For this project, this seems like just unnecessary overhead.

**Pull request closed without merging**
